### PR TITLE
go/format: applying go fmt and organizing the go imports

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**
/kind cleanup

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:
the Code code was not formated according to the go best practices and also did some re-org in the go imports to follow the good practice as well

Follow up PR will be to add a go vet / lint checks, will submit the PR after this gets merged, if get merged.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
go/format: applying go fmt and organizing the go imports
```

### CODE REVIEW

**Comment by leodido** [comment]
kind/cleanup

**Comment by admiral0** [comment]
Thanks for your PR! I implemented it on top of latest sources.

**Comment by cpanato** [comment]
ok

**Pull request closed without merging**
