### PR TITLE
set region when creating the s3 bucket

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**
/kind bug

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

set region when creating the s3 bucket

**Which issue(s) this PR fixes**:

Fixes https://github.com/falcosecurity/kilt/issues/15

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
set region when creating the s3 bucket
```

### CODE REVIEW

**Comment by admiral0** [comment]
This installer is deprecated and will be removed in v0.2.x

I am creating branch `release/0.1.x` to later release v0.1.5 with this fix. Would you mind doing a PR against that?

**Comment by cpanato** [comment]
@admiral0 yes, will close this one and open a new PR
/close

**Comment by cpanato** [comment]
PR opened here: https://github.com/falcosecurity/kilt/pull/21

**Pull request closed without merging**
